<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="1" errors="1" failures="0" skip="0"><testcase classname="concTests.testIWT_AVW.testIWT_AVW" name="test_site1" time="0.047"><error type="selenium.common.exceptions.WebDriverException" message="Message: u'The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://code.google.com/p/chromedriver/downloads/list' ; Stacktrace: Method checkState threw an error in Preconditions.java "><![CDATA[Traceback (most recent call last):
  File "C:\Python27\lib\unittest\case.py", line 318, in run
    self.setUp()
  File "C:\Users\pdam\git\IliaK_Concurrent\src\concTests\testIWT_AVW.py", line 79, in setUp
    "node":config['rc_configuration']['node']})
  File "C:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 67, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 109, in start_session
    'desiredCapabilities': desired_capabilities,
  File "C:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\webdriver.py", line 160, in execute
    self.error_handler.check_response(response)
  File "C:\Python27\lib\site-packages\selenium-2.31.0-py2.7.egg\selenium\webdriver\remote\errorhandler.py", line 149, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: u'The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see http://code.google.com/p/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://code.google.com/p/chromedriver/downloads/list' ; Stacktrace: Method checkState threw an error in Preconditions.java 
]]></error></testcase></testsuite>